name: ipycytoscape
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipycytoscape>=1.0.3
  - jupyterlab=2
  - nodejs
  - networkx
  - pandas
  - sphinx
  - sphinx-copybutton
  - jupyter_sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - nbsphinx-link
